### ISSUE TITLE
Logging vs Performance

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-wasm#108]
### What is wrong.

Using https://github.com/ethereum/py-wasm/pull/87 as a base, here is the benchmark for 10 recursive `keccak` hashes.

```
BENCHMARKING: 10 recursive keccak hashes
took: 2.7963
```

If we remove all of the logging statements from all of the logging functions the results are:

```
BENCHMARKING: 10 recursive keccak hashes
took: 2.2971
```

That is a ~20% speed increase.

The dilema here is:

1. keep logging accept the significant overhead it adds.
2. drop logging statements and gain a solid performance boost at the cost of making debugging significantly harder.

### How can it be fixed

I *think* we can find some middle ground on this, though exactly how it gets implemented is a bit fuzzy.

Ideally, instead of having unconditional calls to `logger.debug` in every logic function, we do them conditionally.

```
# before
def some_logic_fn(config):
    logger.debug(...)
    ...

# after
def some_logic_fn(config):
    if config.logging_enabled:
        logger.debug(...)
    ...
```

This approach produces these benchmark results

```
BENCHMARKING: 10 recursive keccak hashes
took: 2.1372
```

>  This being faster is just a fluke of the imprecision of bencharking, but is demonstrative of this approach being viable to gain performance improvements.

This should cut down on some overhead while still allowing logging to be turned on easily in the test suite and other places.  Anyone have any other ideas?

**Comment by davesque** [comment]
Maybe you've tried this already, but what happens when you disable debug log events in the logging config?  When I look at the actual implementation of `logger.debug` in the `logging` stdlib, if looks to just call into another method `isEnabledFor` which does comparison operation with the log class's integer level value.  So the cost for a disabled logging event is the creation of a couple stack frames, a couple dot lookups, and an integer comparison operation.  Definitely more than a single `if` statement but I wonder what the benchmarks would say.

**Comment by pipermerriam** [comment]
From what I can tell, the overhead is in those mechanisms you listed.  The benchmark is running with `DEBUG` disabled so I believe the base benchmark is indeed representative of what you proposed.

I ended up doing this:

https://github.com/ethereum/py-wasm/pull/109

No rush to merge it, just stabbing at some of the easy low hanging fruit.

**Comment by davesque** [comment]
Okay, here's something we **should not use**...but I thought it was kind of fun:
```
# requirements.txt
macropy3==1.1.0b2
```
```python
# run.py
import macropy.activate  # noqa
import module_with_logging  # noqa
```
```python
# macro_module.py
from ast import Pass
import os

from macropy.core.macros import Macros

macros = Macros()

@macros.block
def noop_when_env_set(tree, **kw):
    print('Checking env var...')

    if os.getenv('LOGGING_DISABLED', False):
        return [Pass()]

    return tree
```
```python
# module_with_logging.py
from macro_module import macros, noop_when_env_set  # noqa

def foo():
    with noop_when_env_set:
        print('Ack!')

foo()
foo()
```
When run from the command line:
```
(macros) Davids-MacBook-Pro-2 ~/projects/macros
$ python run.py
Checking env var...
Ack!
Ack!
(macros) Davids-MacBook-Pro-2 ~/projects/macros
$ LOGGING_DISABLED=1 python run.py
Checking env var...
(macros) Davids-MacBook-Pro-2 ~/projects/macros
$
```

**Comment by davesque** [comment]
What's happening in that example above is that the AST of `module_with_logging` is re-written at import time.  So the print statement isn't just not executed with `LOGGING_DISABLED=1`, it doesn't even exist.

**Comment by pipermerriam** [comment]
That's still quite neat.

**Comment by davesque** [comment]
Yeah. MacroPy is kind of like a beautiful person you wish you could date but you know they're just too wild for you to handle.
