### ISSUE TITLE
Floating point issues

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-wasm#81]
### What is wrong.

In order to be compliant with the spec, we need code that does the following.

- let `A` be the unsigned 64 bit integer: `17293822569102705664`
- let `B` be the 64 bit floating point representation of `A`
- let `C` be the 64 bit integer representation of `B`
- assert `A == C`

**Comment by davesque** [comment]
Where is this requirement described in the spec? I think I could tackle this.

**Comment by pipermerriam** [comment]
Not specifically, it's derived from a failing test.  Specifically the one in `float_exprs.wast.json`, command line `515`

**Comment by pipermerriam** [comment]
More on that failing test:

```
runner.py                  433 DEBUG    running command: line=515  type=<class 'wasm.tools.fixtures.datatypes.AssertReturnCommand'>
runner.py                  148 DEBUG    function_address: 71
control.py                  51 DEBUG    block()
variable.py                 31 DEBUG    get_local()
numeric.py                1159 DEBUG    f64.convert_s/i64(17293822569102705664)
numeric.py                1091 DEBUG    i64.trunc_s/f64(-1.152921504606847e+18)
control.py                 120 DEBUG    end()
control.py                 120 DEBUG    end()
runner.py                  204 DEBUG    expected: 17293822569102705664 | actual: 17293822569102704640
```

You can see it passes through two opcodes, `f64.convert_s/i64 > i64.trunc_s/f64` and the result should be the same as the input.

**Comment by pipermerriam** [comment]
Assuming https://babbage.cs.qc.cuny.edu/IEEE-754.old/64bit.html is correct it suggests pythons float representation is truncating (which isn't surprising).  The binary representation is:

```
0100001111101110000000000000000000000000000000000000010000000000
```

But if you convert `struct.pack('>d', float(17293822569102705664))` to binary it is;
```
0100001111101110000000000000000000000000000000000000000000000000
```

Which you can see there's a bit different between the two.

**Comment by davesque** [comment]
Yeah that extra bit seems to make the difference. It's in the 11th place and that means it represents `2 ** 10 = 1024` which appears to be the difference between the actual and expected values.

**Comment by pipermerriam** [comment]
Murrr, this was really just an incorrectly implemented set of opcodes and then me mis-understanding what was supposed to be happening under the hood.  The correct set of operations which work natively with python constructs is `starting_int -> starting_int_as_signed -> starting_int_as_float -> math.trunc(starting_int_as_float) -> result` which correctly evaluates, ie. `starting_int == s64_to_u64(math.trunc(u64_to_s64(starting_int)))` works correctly.
