### ISSUE TITLE
Convert to use only numpy numerics

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-wasm#82]
### What is wrong.

1. take the integer `2141192192`
1. pack to LE (little-endian) bytes: `struct.pack('<I', 2141192192)`
1. unpack it as a LE float32: `struct.unpack('<f', b'...')[0]`
1. pack that back as a LE float32: `struct.pack('<f', ...)`
1. unpack that back into a uint32: `struct.unpack('<I', b'...')[0]`

Assert that the result is the same as the input........... it isnt...

```python
>>> struct.unpack('<I', struct.pack('<f', struct.unpack('<f', struct.pack('<I', 2141192192))[0]))[0]
2145386496
```

But with numpy everything works as expected.

```python
>>> numpy.frombuffer(numpy.frombuffer(numpy.uint32(2141192192).tobytes(), numpy.float32)[0].tobytes(), numpy.uint32)[0]
2141192192
```

Not entirely sure what is happening under the hood, but python isn't preserving the bytes representation for `NAN` values and numpy does it right.  There are also a **lot** of other benefits we get for free from this conversion, primarily better/easier typing, native `value.tobytes()` methods, native overflow wrapping and proper bounds checking.

**Comment by davesque** [comment]
For fun, I tracked down the reason for this.  It's made apparent by the fact that using double-width values preserves the bits:
```python
In [56]: struct.unpack('>Q', struct.pack('>d', struct.unpack('>d', struct.pack('>Q', 2141192192))[0]))[0]
Out[56]: 2141192192
```

Apparently, python [stores float values internally as doubles](https://github.com/python/cpython/blob/master/Include/floatobject.h#L17).

When you do `struct.unpack('<f', ...)`, an actual 32-bit float only exists as long as is needed to set the `ob_fval` in the internal `PyFloatObject` struct equal to that 32-bit value.  When that happens, the internal hardware of the processor probably does some rounding or magic to convert the 32-bit `nan` value into a 64-bit one.

By the time the internal double gets converted back to a float for packing, the extra bit has showed up in the highest-order fractional place of the internal float representation.

Here's a small C program that duplicates the issue:
```c
#include<stdio.h>
#include<string.h>

float make_float(
    unsigned char b0,
    unsigned char b1,
    unsigned char b2,
    unsigned char b3
) {
  float x;

  unsigned char *p = (unsigned char *)&x;

  p[0] = b0;
  p[1] = b1;
  p[2] = b2;
  p[3] = b3;

  return x;
}

void print_bits(unsigned char p) {
  printf(p & 1 ? "1" : "0");
  printf(p & 2 ? "1" : "0");
  printf(p & 4 ? "1" : "0");
  printf(p & 8 ? "1" : "0");
  printf(p & 16 ? "1" : "0");
  printf(p & 32 ? "1" : "0");
  printf(p & 64 ? "1" : "0");
  printf(p & 128 ? "1" : "0");
}

void print_bytes(unsigned char *p, unsigned int n) {
  for (unsigned int i = 0; i < n; i++) {
    print_bits(p[i]);
    printf(" ");
  }
  printf("\n");
}

int main(void) {
  float x = make_float(0x00, 0x00, 0xa0, 0x7f);
  double y = x;
  float z = y;

  printf("%f\n", x);
  print_bytes((unsigned char *)&x, 4);

  printf("%f\n", z);
  print_bytes((unsigned char *)&z, 4);
}
```

Its output:
```
Davids-MacBook-Pro ~
$ ./a.out
nan
00000000 00000000 00000101 11111110
nan
00000000 00000000 00000111 11111110
```

**Comment by pipermerriam** [comment]
Done in https://github.com/ethereum/py-wasm/pull/83
