### ISSUE TITLE
Consider using custom dtypes over numpy builtins

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-wasm#95]
### What is wrong?

The types provided by numpy default to the endianness of the machine.  I.E., if the machine's native floating point is big-endian, then `numpy.float32` will also default to big endian.

WASM **always** wants littleendian.

### How can it be fixed.

Short term, we can add an import-time assertion:

```python
# wasm/__init__.py
import sys
assert sys.byteorder == 'little'
```

Long term we should replace all usage of numpy types with the following equivalents which aren't succeptable to the underlying hardware being the wrong endianness

- `numpy.uint32` -> `numpy.dtype('<u4')`
- `numpy.uint64` -> `numpy.dtype('<u8')`
- `numpy.int32` -> `numpy.dtype('<i4')`
- `numpy.int64` -> `numpy.dtype('<i8')`
- `numpy.float32` -> `numpy.dtype('<f4')`
- `numpy.float64` -> `numpy.dtype('<f8')`

**Comment by davesque** [comment]
We already had a short discussion about this where you pointed out that WASM binaries encode values in little-endian order.  So there's definitely a need to be explicit about this in certain cases.

I wanted to be sure and point out that I think there's some value in letting numpy do its thing once it has a value that it can use.  In other words, we only care about endianness when decoding or encoding values, but not when doing arithmetic with them or anything like that.  I don't even know if numpy supports doing arithmetic operations with a different internal byte order, but, if it does, I imagine there's a performance cost involved.
