### ISSUE TITLE
Iterators (co-routines) with side-effects considered harmful

### ISSUE THREAD

**Issue by davesque** [ethereum/py-wasm#96]
https://github.com/ethereum/py-wasm/blob/5535a34672789e68f49a1944df76ed7bacf3e0a6/wasm/parsers/leb128.py#L58-L75

I feel like there might be a potential anti-pattern here.  The problem is that we have an iterator with side-effects.  Imagine if we instantiated such an iterator, obtained some values from it, did some other things that mutate the cursor of the stream, and then are surprised when get more values from the iterator later after it tried to do something with the stream at the new cursor position.

Another way to say this is that the semantics of the iterator imply that it should always be immediately consumed until `StopIteration`.  So why not just make it a function that does that?

**Comment by davesque** [comment]
In this particular case, it doesn't matter because the iterator is only ever converted straight to a tuple.  I'm more just trying to call attention to something we should maybe avoid doing in the future.

**Comment by davesque** [comment]
Another way to say this is that the semantics of the iterator imply that it should always be immediately consumed until `StopIteration`.  So why not just make it a function that does that?

**Comment by pipermerriam** [comment]
This was me avoiding the `eth-utils` dependency and finding a way to semi-replecate the `to_tuple` decorator.  I think I may just vendor a `to_tuple` decorator into this library as it would allow me to clean up a few of these paired functions.

**Comment by pipermerriam** [comment]
this has been fixed in #101
