### ISSUE TITLE
Wrong exception message in int parsers

### ISSUE THREAD

**Issue by davesque** [ethereum/py-wasm#97]
https://github.com/ethereum/py-wasm/blob/5535a34672789e68f49a1944df76ed7bacf3e0a6/wasm/parsers/integers.py#L33-L36

Exception message is wrong.  Should say that max is 5.  The same issue exists with `parse_u32`.  Will get back to this later after reviewing PR #83 .

**Comment by pipermerriam** [comment]
Cleaned up in https://github.com/ethereum/py-wasm/pull/83
